---
title: "NBA"
author: "Pei-Chi Hung"
date: "2022-08-30"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(janitor)
```

```{r}
# read in data files 
# combine shoot forward, center and guard data 
shot_dash_forward <- read.csv("shoot_dash_forward.csv")
shot_dash_center <- read.csv("shoot_dash_center.csv")
shot_dash_guard <- read.csv("shoot_dash_guard.csv")

shot_dash_forward_clean <- shot_dash_forward %>% 
  row_to_names(1) %>% 
  select(-1) %>% 
  rename(Season = `2021-2022`) %>% 
  filter(Player != "Player") %>% 
  mutate(Season = substr(Season, 1, 4),
         Position = "Forward") 

shot_dash_center_clean <- shot_dash_center %>% 
  row_to_names(1) %>% 
  select(-1) %>% 
  rename(Season = `2021-2022`) %>% 
  filter(Player != "Player") %>% 
  mutate(Season = substr(Season, 1, 4),
         Position = "Center")

shot_dash_guard_clean <- shot_dash_guard %>% 
  row_to_names(1) %>% 
  select(-1) %>% 
  rename(Season = `2021-2022`) %>% 
  filter(Player != "Player") %>% 
  mutate(Season = substr(Season, 1, 4),
         Position = "Guard")

shot_position_clean <- rbind(shot_dash_forward_clean, shot_dash_center_clean) %>% rbind(shot_dash_guard_clean)

write.csv(shot_position_clean,"C:\\NBA\\shot_position_clean.csv", row.names = TRUE)
```

```{r}
# read in files 
tr_stats <- read.csv("trad_stats.csv") 

# rename column names 
tr_stats_clean <- tr_stats %>% 
  select(-c(DD2:X....RANK)) %>% 
  select(-X, -V1) %>% 
  rename(`FG%` = FG.,
         `3PM%`= X3PM,
         `3PA` = X3PA, 
         `3P%` = X3P.,
         `FT%` = FT.)
```

```{r}
# transform into long format
tr_long <- tr_stats_clean %>% 
  select(PLAYER, Season, FG., AST, REB, STL, BLK) %>% 
  pivot_longer(cols = FG.:BLK,
               names_to = "Matrix",
               values_to = "Value")
write.csv(tr_long,"C:\\NBA\\tr_long.csv", row.names = TRUE)

# transform in to wide format
tr_wide <- tr_stats_clean %>% 
  select(PLAYER, AST, FG., REB, STL, BLK, Season) %>% 
  mutate(`AST%`= AST/max(AST),
         `FG%`= FG./max(FG.),
         `REB%` = REB/max(REB),
         `STL%` = STL/max(STL),
         `BLK%` = BLK/max(BLK),
         Season = substr(Season, 1, 4)) %>% 
  filter(Season == 2021)
  
write.csv(tr_wide,"C:\\NBA\\tr_wide.csv", row.names = TRUE)

```



